<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{4df7eff0-0a82-4582-95f2-d69fae3df5f6}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbMachine : FB_Machine;
	bTest : BOOL;
	bb : BOOL;
	bb2 : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbMachine();
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="66" Count="0" />
      <LineId Id="48" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>